name: z80
description: >
  This is an emulator for the Zilog Z80 microprocessor, 
  it is a simple, straightforward instruction interpreter.
version: 0.2.3
homepage: https://github.com/slightfoot/dart_z80
maintainer: Simon Lightfoot (@slightfoot)

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
