name: z80
version: 0.1.0
description: Emulator for the Zilog Z80 microprocessor.
homepage: https://github.com/slightfoot/dart_z80
maintainer: Simon Lightfoot (@slightfoot)

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
